databases:
  - name: hot-tail
    databaseName: hot_tail
    user: hot_tail

services:
  - type: web
    name: hot-tail
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hot-tail
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
